import { Sidebar } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black`}>
        <div className="justify-between flex pt-2 pb-2 ps-2 pe-2">
          <p className="dark:text-white text-black font-bold">Khamphamviet</p>
          <Sidebar />
        </div>
        {children}
      </body>
    </html>
  );
}
